### ISSUE TITLE
linter should walk from file path up to find .jadelintrc

### ISSUE THREAD

**Issue by ghost** [rrdelaney/jadelint#14]
per d9d/atom-linter-jade#3, the linter only looks in the current directory for the `.jadelintrc` file.  It should start from the file directory (not cwd) and walk up.

This is also an issue from the command line if calling the linter on a file in a different directory, e.g.:

``` sh
jadelint src/file.jade
```

Alternatively, can you fork the config file loading code so that I can easily do something like `.setConfig(json|fileName)` and not have to duplicate this block of code:

``` js
try {
  conf = JSON.parse(fs.readFileSync('.jadelintrc'));
  try {
    for (rule in conf) {
      level = conf[rule];
      rules.rules[rule].prototype.level = level;
    }
  } catch (_error) {}
} catch (_error) {}
```

**Comment by ghost** [comment]
And upon fixing this for my linter plugin, I realized that there is a single global rules object.  This basically makes it impossible to selectively enable/disable rules in a single process (e.g. without restarting node) without resorting to absurdly ugly hacks like changing `rule[name].prototype.level` and then resetting it after the linter runs.

**Comment by rrdelaney** [comment]
jadelint will have support for config objects in version 0.3

**Comment by dustinblackman** [comment]
:+1:

**Comment by rrdelaney** [comment]
I just release v0.3. The linter doesn't look up the tree for a .jadelintrc, but you can provide your own config object. I recommend looking at the [API documentation](http://rdel.io/jadelint/api). If you need help implementing the linter with the new API, I made a [gitter room](https://gitter.im/rrdelaney/jadelint?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by ghost** [comment]
Thanks, I don't think this issue should be closed though.

``` sh
jadelint src/file.jade
```

doesn't work.

**Comment by rrdelaney** [comment]
I just tried that locally, and it worked fine.

Can you run `npm ls -g jadelint` and also tell me what OS you are on?

**Comment by ghost** [comment]
Okay, sorry -- it now works as long as the `.jadelintrc` is in the same directory.  That's not a very useful setup to me :)  I currently have about 30 folders under one `views` folder in a project.  It's not feasible to copy the `.jadelintrc` to every one

The linter working is a different piece.

**Comment by rrdelaney** [comment]
I'm working on a linter that will move up the dir tree now

**Comment by ghost** [comment]
Can I suggest taking a look at eslint and maybe stealing code from it?

It does a very beautiful thing where it merges config files up the tree.

**Comment by rrdelaney** [comment]
That functionality has been added. I haven't tested it on a windows machine, but it should work fine on a *nix device. Try it in v0.3.2
