### ISSUE TITLE
SVG use: No namespacing of attributes attribute allowed

### ISSUE THREAD

**Issue by strarsis** [rrdelaney/jadelint#18]
"No namespacing of attributes attribute allowed"
http://rdel.io/jadelint/api/class/NoXMLAttributeNamespace.html

I add a SVG element in jade using 

```
svg: use(xlink:href='/images/sprite.symbol.svg#test')
```

xlink:href is the proper approach for adding SVGs this way,
so jadelint should make an exception here.

**Comment by rrdelaney** [comment]
I added an exception for things namespaced under xlink on the rule. Should reflect in v0.3.3 which I just pushed
