### ISSUE TITLE
Feature Request: provide a node interface

### ISSUE THREAD

**Issue by ghost** [rrdelaney/jadelint#6]
In the meantime, I'd propose not using `process.exit` so that the linter can be included

**Comment by rrdelaney** [comment]
Hey there :) so in my package.json i specify the Linter class as my main file https://github.com/rrdelaney/jadelint/blob/master/src/Linter.coffee so it should be pretty easy to play around with. 

There's doc blocks all around the source, and I'd be glad to help you make that work for your linter, but for a quick example check out https://github.com/rrdelaney/grunt-jadelint/blob/master/tasks/jadelint.js

**Comment by rrdelaney** [comment]
You can also find the generated API docs at http://ryandelaney.io/jadelint/api/
