### ISSUE TITLE
Problem with html5 tags with attributes without values

### ISSUE THREAD

**Issue by patwork** [rrdelaney/jadelint#8]
Hello,

Looks like jadelint doesn't like tags with attributes without values, which are ok with jade and html5 [specification](http://www.w3.org/html/wg/drafts/html/master/syntax.html#attributes-2).

Example jade file:

`
script(src="nope.js", async, defer)
`

Error:

> /tmp/node_modules/jadelint/node_modules/text-table/index.js:59
>     return m ? m.index + 1 : c.length;
> 
> TypeError: Cannot read property 'length' of undefined
>     at dotindex (/tmp/node_modules/jadelint/node_modules/text-table/index.js:59:31)
>     at /tmp/node_modules/jadelint/node_modules/text-table/index.js:11:21
>     at Array.forEach (native)
>     at forEach (/tmp/node_modules/jadelint/node_modules/text-table/index.js:73:31)
>     at /tmp/node_modules/jadelint/node_modules/text-table/index.js:10:9
>     at Array.reduce (native)
>     at reduce (/tmp/node_modules/jadelint/node_modules/text-table/index.js:63:30)
>     at module.exports (/tmp/node_modules/jadelint/node_modules/text-table/index.js:9:20)
>     at Reporter.aggregate (/tmp/node_modules/jadelint/target/Reporter.js:23:16)
>     at module.exports.jadelint (/tmp/node_modules/jadelint/target/jadelint.js:44:16)

**Comment by rrdelaney** [comment]
Investigating now

**Comment by rrdelaney** [comment]
Fixed and published to npm. If you find any other bugs or have feature requests please don't hesitate to reach out :smile:

**Comment by patwork** [comment]
That was quick, thanks :)

But... sorry to bother you, there's new problem and it's a quite strange one. I'm assuming you're working in windows? After you've changed bin/jadelint it's no longer working in linux (ubuntu) because of CRLF line endings.

`
#!/usr/bin/env node<CR><LF>
`

Silly env is looking for "node<CR>" file and returns error.

**Comment by rrdelaney** [comment]
I have a split dev env between the two, but it seemed to work on my Linux machine fine last time I used it. I will update it now though.

**Comment by rrdelaney** [comment]
Version 0.2.10 should fix your issues

**Comment by patwork** [comment]
✔ No problems found!

great :+1:

**Comment by rrdelaney** [comment]
Glad I could help. If you have any feature requests, please make issues :)
